# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 14:03
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XGoods',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False, verbose_name='Goods Id')),
                ('prize', models.FloatField(blank=True, verbose_name='价格')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='网址')),
                ('intro', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='说明')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name_plural': '商品管理',
                'verbose_name': '商品',
            },
        ),
        migrations.CreateModel(
            name='XStore',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='网址')),
                ('intro', models.TextField(default='', verbose_name='Introduce')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': '商家管理',
                'verbose_name': '商家',
            },
        ),
        migrations.AddField(
            model_name='xgoods',
            name='xstores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xstores.XStore', verbose_name='商家'),
        ),
    ]
