# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xstores', '0003_auto_20161128_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='xstore',
            name='home_display',
            field=models.BooleanField(default=False, verbose_name='首页显示'),
        ),
        migrations.AddField(
            model_name='xstore',
            name='nav_display',
            field=models.BooleanField(default=False, verbose_name='导航显示'),
        ),
    ]
